import type {Metadata} from "next";
import {Geist, Geist_Mono, Inter} from "next/font/google";
import "./globals.css";
import {HeaderComponent} from "@/components/header";
import {SidebarComponent} from "@/components/sidebar";

const inter = Inter({
	weight: ["300", "400", "500", "600", "700"],
	subsets: ["latin"],
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en" className="light">
			<body className={`${inter.className} antialiased`}>
				<section className="flex items-start bg-[#f5f9fc]">
					<SidebarComponent />
					<div className="w-full">
						<HeaderComponent />
						{children}
					</div>
				</section>
			</body>
		</html>
	);
}
